//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrox.ProCSharp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Circuit
    {
        public Circuit()
        {
            this.Races = new HashSet<Race>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Country { get; set; }
    
        public virtual ICollection<Race> Races { get; set; }
    }
}
