//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrox.ProCSharp.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Formula1Entities : DbContext
    {
        public Formula1Entities()
            : base("name=Formula1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Circuit> Circuits { get; set; }
        public DbSet<RaceResult> RaceResults { get; set; }
        public DbSet<Racer> Racers { get; set; }
        public DbSet<Race> Races { get; set; }
    }
}
