//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrox.ProCSharp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaceResult
    {
        public int Id { get; set; }
        public int RaceId { get; set; }
        public int RacerId { get; set; }
        public int TeamId { get; set; }
        public int Position { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> Grid { get; set; }
        public Nullable<decimal> Points { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public Nullable<int> Laps { get; set; }
        public string Retired { get; set; }
    
        public virtual Race Race { get; set; }
        public virtual Racer Racer { get; set; }
    }
}
