//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wrox.ProCSharp.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Racer
    {
        public Racer()
        {
            this.RaceResults = new HashSet<RaceResult>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Nationality { get; set; }
        public Nullable<int> Starts { get; set; }
        public Nullable<int> Wins { get; set; }
        public Nullable<int> Points { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<System.DateTime> DateOfDeath { get; set; }
    
        public virtual ICollection<RaceResult> RaceResults { get; set; }
    }
}
